const features = [
  {
    icon: "🗺️",
    title: "AI Roadmap",
    desc: "Get a personalised week-by-week learning plan generated by AI for your chosen skill and level.",
    gradient: "from-purple-500 to-indigo-600",
    bg: "bg-purple-950/40",
    border: "border-purple-900/40",
  },
  {
    icon: "📈",
    title: "Progress tracking",
    desc: "Visual dashboards show your streaks, completion rates, and where you stand in each sprint.",
    gradient: "from-emerald-500 to-teal-600",
    bg: "bg-emerald-950/40",
    border: "border-emerald-900/40",
  },
  {
    icon: "🧠",
    title: "AI Quizzes",
    desc: "Test your knowledge with auto-generated quizzes after every milestone. Get instant feedback.",
    gradient: "from-amber-500 to-orange-600",
    bg: "bg-amber-950/40",
    border: "border-amber-900/40",
  },
  {
    icon: "🏆",
    title: "Gamified levels",
    desc: "Progress through levels like a game. Unlock badges and see your rank among learners.",
    gradient: "from-pink-500 to-rose-600",
    bg: "bg-pink-950/40",
    border: "border-pink-900/40",
  },
]

function Features() {
  return (
    <section id="features" className="bg-[#080512] border-y border-white/[0.04] py-24 px-6 relative overflow-hidden">
      {/* Drifting Neon Blobs for depth */}
      <div className="absolute top-1/4 right-0 w-80 h-80 bg-purple-500/5 rounded-full blur-[80px] pointer-events-none"></div>

      <div className="text-center mb-16 relative z-10">
        <span className="text-purple-400 font-semibold text-sm uppercase tracking-widest">Why SkillSprint</span>
        <h2 className="text-4xl font-extrabold text-slate-100 mt-3">
          Everything you need to{" "}
          <span className="gradient-text">level up</span>
        </h2>
        <p className="text-slate-400 mt-4 text-lg max-w-xl mx-auto">
          SkillSprint combines AI, structured learning, and gamification into one platform.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 max-w-6xl mx-auto relative z-10">
        {features.map(f => (
          <div key={f.title} className="glass-panel card-hover rounded-2xl p-6 relative overflow-hidden">
            <div className={`absolute top-0 right-0 w-24 h-24 bg-gradient-to-br ${f.gradient} opacity-5 rounded-full -mr-8 -mt-8`}></div>
            <div className={`${f.bg} w-14 h-14 rounded-2xl flex items-center justify-center text-3xl mb-5 border ${f.border}`}>
              {f.icon}
            </div>
            <h3 className="font-bold text-slate-100 text-lg mb-2">{f.title}</h3>
            <p className="text-sm text-slate-400 leading-relaxed font-medium">{f.desc}</p>
            <div className={`mt-5 h-1 w-12 rounded-full bg-gradient-to-r ${f.gradient}`}></div>
          </div>
        ))}
      </div>
    </section>
  )
}

export default Features